#!/bin/bash

VER=0.9.5
if [ ! -f pbzip2-$VER.tar.gz ]; then
    wget http://pkgs.fedoraproject.org/repo/pkgs/pbzip2/pbzip2-$VER.tar.gz/94cbc6ff49a6f4df40f6b1552b613ce6/pbzip2-$VER.tar.gz
fi
if [ ! -f input.tar ]; then
    wget http://download.oracle.com/berkeley-db/db-5.3.15.tar.gz
fi
gunzip -f db-5.3.15.tar.gz
mv db-5.3.15.tar input.tar

rm -rf tsan1
mkdir tsan1
pushd tsan1
tar zxvf ../pbzip2-$VER.tar.gz
pushd pbzip2-$VER
patch -p1 < ../../add-xtern-annot-0.9.5-all.patch
patch -p1 < ../../add-set-base-time-annot.patch
make
cp pbzip2 ../pbzip2
popd

