#!/bin/bash

VER=0.9.5
if [ ! -f pbzip2-$VER.tar.gz ]; then
    wget http://pkgs.fedoraproject.org/repo/pkgs/pbzip2/pbzip2-$VER.tar.gz/94cbc6ff49a6f4df40f6b1552b613ce6/pbzip2-$VER.tar.gz
fi
if [ ! -f input.tar ]; then
    wget http://download.oracle.com/berkeley-db/db-5.3.15.tar.gz
fi
gunzip -f db-5.3.15.tar.gz
mv db-5.3.15.tar input.tar

rm -rf tsan2
mkdir tsan2
pushd tsan2
wget http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
tar xvzf bzip2-1.0.6.tar.gz
tar zxvf ../pbzip2-$VER.tar.gz
pushd bzip2-1.0.6
make CC="clang -fsanitize=thread -fPIE" LDFLAGS="-fsanitize=thread -pie"
cp libbz2.a ../pbzip2-$VER
popd
pushd pbzip2-$VER
make CC="clang++ -fsanitize=thread -fPIE -pie" pbzip2-static
cp pbzip2 ../pbzip2
popd

