#!/bin/bash
set -e
APP_DIR=`pwd`
VER=2.4.33
if [ ! -f openldap-$VER.tgz ]; then
    wget http://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-$VER.tgz
fi

rm -rf tsan1
mkdir tsan1
cd tsan1
tar zxvf ../openldap-$VER.tgz

# Build.
cd openldap-$VER
patch -p1 < ../../add-resp-to-mtread.patch
mkdir obj
cd obj
CFLAGS="-g -O0" ../configure --prefix=$APP_DIR/tsan1/install
make -j25
make install -j25
cd $APP_DIR
# We use this one because it has debug symbols.
ln -s $APP_DIR/xtern-test-mt-hot $APP_DIR/tsan1/openldap-$VER/tests/scripts/xtern-test-mt-hot
ln -s $APP_DIR/local.options $APP_DIR/tsan1/openldap-$VER/obj/tests/local.options
ln -s $APP_DIR/tsan1/openldap-$VER/obj/servers/slapd/slapd $APP_DIR/tsan1/install/libexec/slapd.x86
cp $APP_DIR/tsan1/install/etc/openldap/slapd.conf $APP_DIR/tsan1/install/etc/openldap/slapd.conf.bak
cp slapd.conf.template $APP_DIR/tsan1/install/etc/openldap/slapd.conf

# Add benchmark.
cd tsan1/openldap-$VER
patch -p1 < ../../only-xtern-test-mt-hot.patch
patch -p1 < ../../only-run-bdb-tests.patch
cd $APP_DIR/tsan1
ln -s $APP_DIR/tsan1/openldap-$VER/obj/servers/slapd/slapd
ln -s $APP_DIR/tsan1/openldap-$VER/obj/tests/progs/slapd-mtread

cd openldap-$VER/obj/tests
make test
sed -i -e "s/\.\//tsan1\/openldap-${VER}\/obj\/tests\//g" testrun/slapd.1.conf
